imports:
    - { resource: ../../../TestBundle/Resources/config/twig.yml }

services:
    coreshop.frontend.controller.abstract:
        class: CoreShop\Bundle\FrontendBundle\Controller\FrontendController
        calls:
            - [setContainer, ['@service_container']]
            - [setTemplateConfigurator, ['@CoreShop\Bundle\FrontendBundle\TemplateConfigurator\TemplateConfiguratorInterface']]

    CoreShop\Bundle\FrontendBundle\TemplateConfigurator\TemplateConfiguratorInterface: '@CoreShop\Bundle\FrontendBundle\TemplateConfigurator\TemplateConfigurator'
    CoreShop\Bundle\FrontendBundle\TemplateConfigurator\TemplateConfigurator:
        public: true
        arguments:
            - '%coreshop.frontend.view_bundle%'
            - '%coreshop.frontend.view_suffix%'

    CoreShop\Bundle\FrontendBundle\Twig\LocaleSwitcherExtension:
        arguments:
            - '@Pimcore\Model\Document\Service'
            - '@CoreShop\Component\Core\Context\ShopperContextInterface'
            - '@Symfony\Component\HttpFoundation\RequestStack'
            - '@router'
        tags:
            - { name: twig.extension }

    CoreShop\Bundle\FrontendBundle\Twig\MergeRecursiveExtension:
        tags:
            - { name: twig.extension }

    CoreShop\Bundle\FrontendBundle\Twig\TypeCastExtension:
        tags:
            - { name: twig.extension }
