parameters:
  coreshop.frontend.base.url: /test/shop

services:
  coreshop.frontend.controller.customer:
    class: CoreShop\Bundle\FrontendBundle\Controller\CustomerController
    calls:
      - [setContainer, ['@service_container']]

  coreshop.frontend.controller.currency:
    class: CoreShop\Bundle\FrontendBundle\Controller\CurrencyController
    calls:
      - [setContainer, ['@service_container']]

  coreshop.frontend.controller.language:
    class: CoreShop\Bundle\FrontendBundle\Controller\LanguageController
    calls:
      - [setContainer, ['@service_container']]

  coreshop.frontend.controller.search:
    class: CoreShop\Bundle\FrontendBundle\Controller\SearchController
    calls:
      - [setContainer, ['@service_container']]

  coreshop.frontend.controller.cart:
    class: CoreShop\Bundle\FrontendBundle\Controller\CartController
    calls:
      - [setContainer, ['@service_container']]

  coreshop.frontend.controller.checkout:
    class: CoreShop\Bundle\FrontendBundle\Controller\CheckoutController
    arguments:
      - '@coreshop.checkout_manager'
    calls:
      - [setContainer, ['@service_container']]

  coreshop.frontend.controller.category:
    class: CoreShop\Bundle\FrontendBundle\Controller\CategoryController
    calls:
      - [setContainer, ['@service_container']]

  coreshop.frontend.controller.product:
    class: CoreShop\Bundle\FrontendBundle\Controller\ProductController
    calls:
      - [setContainer, ['@service_container']]

  coreshop.frontend.controller.security:
    class: CoreShop\Bundle\FrontendBundle\Controller\SecurityController
    arguments:
      - '@security.authentication_utils'
      - '@form.factory'
      - '@templating'
    calls:
      - [setContainer, ['@service_container']]