parameters:
  coreshop.frontend.base.url: /test/shop

services:
  coreshop.frontend.controller.index:
    class: CoreShop\Bundle\FrontendBundle\Controller\IndexController
    calls:
      - [setContainer, ['@service_container']]

  coreshop.frontend.controller.register:
    class: CoreShop\Bundle\FrontendBundle\Controller\RegisterController
    calls:
      - [setContainer, ['@service_container']]

  coreshop.frontend.controller.customer:
    class: CoreShop\Bundle\FrontendBundle\Controller\CustomerController
    calls:
      - [setContainer, ['@service_container']]

  coreshop.frontend.controller.currency:
    class: CoreShop\Bundle\FrontendBundle\Controller\CurrencyController
    calls:
      - [setContainer, ['@service_container']]

  coreshop.frontend.controller.language:
    class: CoreShop\Bundle\FrontendBundle\Controller\LanguageController
    calls:
      - [setContainer, ['@service_container']]

  coreshop.frontend.controller.search:
    class: CoreShop\Bundle\FrontendBundle\Controller\SearchController
    calls:
      - [setContainer, ['@service_container']]

  coreshop.frontend.controller.cart:
    class: CoreShop\Bundle\FrontendBundle\Controller\CartController
    calls:
      - [setContainer, ['@service_container']]

  coreshop.frontend.controller.checkout:
    class: CoreShop\Bundle\FrontendBundle\Controller\CheckoutController
    arguments:
      - '@coreshop.checkout_manager'
    calls:
      - [setContainer, ['@service_container']]

  coreshop.frontend.controller.category:
    class: CoreShop\Bundle\FrontendBundle\Controller\CategoryController
    calls:
      - [setContainer, ['@service_container']]

  coreshop.frontend.controller.product:
    class: CoreShop\Bundle\FrontendBundle\Controller\ProductController
    calls:
      - [setContainer, ['@service_container']]

  coreshop.frontend.controller.quote:
    class: CoreShop\Bundle\FrontendBundle\Controller\QuoteController
    calls:
      - [setContainer, ['@service_container']]

  coreshop.frontend.controller.security:
    class: CoreShop\Bundle\FrontendBundle\Controller\SecurityController
    arguments:
      - '@security.authentication_utils'
      - '@form.factory'
      - '@templating'
    calls:
      - [setContainer, ['@service_container']]

  coreshop.frontend.controller.payment:
    class: CoreShop\Bundle\PayumBundle\Controller\PaymentController
    arguments:
      - '@coreshop.factory.payment'
      - '@coreshop.repository.order'
      - '@coreshop.object_service'
      - '@coreshop.context.currency'
      - '@doctrine.orm.entity_manager'
    calls:
            - [setContainer, ['@service_container']]