imports:
    - { resource: "services/wishlist.yml" }

services:
    coreshop.frontend.controller.abstract:
        class: CoreShop\Bundle\FrontendBundle\Controller\FrontendController
        abstract: true
        calls:
            - [setContainer, ['@service_container']]
            - [setTemplateConfigurator, ['@coreshop.frontend.template_configurator']]

    coreshop.frontend.template_configurator:
        class: CoreShop\Bundle\FrontendBundle\TemplateConfigurator\TemplateConfigurator
        public: true
        arguments:
            - '%coreshop.frontend.view_bundle%'
            - '%coreshop.frontend.view_suffix%'

    coreshop.frontend.twig.locale_switcher:
        class: CoreShop\Bundle\FrontendBundle\Twig\LocaleSwitcherExtension
        arguments:
            - '@Pimcore\Model\Document\Service'
            - '@coreshop.context.shopper'
        tags:
            - { name: twig.extension }
