routes:
  coreshop_index:
    pattern: "/(\\w+)\\/shop(\\/?)$/"
    reverse: "/%_locale/shop"
    controller: "@coreshop.frontend.controller.index:index"
    variables: _locale
    priority: 1

  coreshop_category_list:
    pattern: "/(\\w+)\\/shop\\/(.*?)\\~c([0-9]+)$/"
    reverse: "/%_locale/shop/%name~c%category"
    controller: "@coreshop.frontend.controller.category:index"
    variables: _locale,name,category
    priority: 2

  coreshop_product_detail:
    pattern: "/(\\w+)\\/shop\\/(.*?)\\~p([0-9]+)$/"
    reverse: "/%_locale/shop/%name~p%product"
    controller: "@coreshop.frontend.controller.product:detail"
    variables: _locale,name,product
    priority: 2

  coreshop_cart_summary:
    pattern: "/(\\w+)\\/shop\\/cart$/"
    reverse: "/%_locale/shop/cart"
    controller: "@coreshop.frontend.controller.cart:summary"
    variables: _locale
    priority: 2

  coreshop_cart_add:
    methods:
      - POST
    pattern: "/(\\w+)\\/shop\\/cart\\/add\\/([0-9]+)$/"
    reverse: "/%_locale/shop/cart/add/%product"
    controller: "@coreshop.frontend.controller.cart:addItem"
    variables: _locale,product
    priority: 3

  coreshop_partial_cart_add:
    pattern: "/(\\w+)\\/_partial\\/cart\\/add\\/([0-9]+)$/"
    reverse: "/%_locale/_partial/cart/add/%product"
    controller: "@coreshop.frontend.controller.cart:addItem"
    variables: _locale,product
    priority: 3

  coreshop_cart_remove:
    pattern: "/(\\w+)\\/shop\\/cart\\/remove\\/([0-9]+)$/"
    reverse: "/%_locale/shop/cart/remove/%cartItem"
    controller: "@coreshop.frontend.controller.cart:removeItem"
    variables: _locale,cartItem
    priority: 3

  coreshop_cart_remove_price_rule:
    pattern: "/(\\w+)\\/shop\\/cart\\/remove-price-rule$/"
    reverse: "/%_locale/shop/cart/remove-price-rule"
    controller: "@coreshop.frontend.controller.cart:removePriceRule"
    variables: _locale
    priority: 3

  coreshop_cart_check_shipment:
    pattern: "/(\\w+)\\/shop\\/cart\\/shipment-calculation$/"
    reverse: "/%_locale/shop/cart/shipment-calculation"
    controller: "@coreshop.frontend.controller.cart:shipmentCalculation"
    variables: _locale
    priority: 3

  coreshop_login:
    pattern: "/(\\w+)\\/shop\\/login$/"
    reverse: "/%_locale/shop/login"
    controller: "@coreshop.frontend.controller.security:login"
    variables: _locale
    priority: 2

  coreshop_login_check:
    pattern: "/(\\w+)\\/shop\\/login-check$/"
    reverse: "/%_locale/shop/login-check"
    controller: "@coreshop.frontend.controller.security:check"
    variables: _locale
    priority: 3

  coreshop_logout:
    pattern: "/(\\w+)\\/shop\\/logout$/"
    reverse: "/%_locale/shop/logout"
    controller: "@coreshop.frontend.controller.security:logout"
    variables: _locale
    priority: 2

  coreshop_cart_create_qoute:
    pattern: "/(\\w+)\\/shop\\/cart\\/quote$/"
    reverse: "/%_locale/shop/cart/quote"
    controller: "@coreshop.frontend.controller.cart:createQuote"
    variables: _locale
    priority: 3

  coreshop_quote_detail:
    pattern: "/(\\w+)\\/shop\\/quote\\~q([0-9]+)$/"
    reverse: "/%_locale/shop/quote~q%quote"
    controller: "@coreshop.frontend.controller.quote:show"
    variables: _locale,quote
    priority: 2

  coreshop_checkout:
    pattern: "/(\\w+)\\/shop\\/checkout\\/(.*)$/"
    reverse: "/%_locale/shop/checkout/%stepIdentifier"
    controller: "@coreshop.frontend.controller.checkout:process"
    variables: _locale,stepIdentifier
    priority: 2

  coreshop_order_revise:
    pattern: "/(\\w+)\\/shop\\/order\\/revise\\/(.*)$/"
    reverse: "/%_locale/shop/order/revise/%token"
    controller: "@coreshop.frontend.controller.order:revise"
    variables: _locale,token
    priority: 2

  coreshop_order_revise_pay:
    pattern: "/(\\w+)\\/shop\\/order\\/revise\\/(.*)\\/pay$/"
    reverse: "/%_locale/shop/order/revise/%token/pay"
    controller: "@coreshop.frontend.controller.payment:prepareCapture"
    variables: _locale,token
    priority: 3

  coreshop_checkout_do:
    pattern: "/(\\w+)\\/shop\\/checkout-do$/"
    reverse: "/%_locale/shop/checkout-do"
    controller: "@coreshop.frontend.controller.checkout:doCheckout"
    variables: _locale
    priority: 2

  coreshop_checkout_confirmation:
    pattern: "/(\\w+)\\/shop\\/checkout-thank-you$/"
    reverse: "/%_locale/shop/checkout-thank-you"
    controller: "@coreshop.frontend.controller.checkout:thankYou"
    variables: _locale
    priority: 2

  coreshop_payment:
    pattern: "/(\\w+)\\/shop\\/pay\\/([0-9]+)$/"
    reverse: "/%_locale/shop/pay/%order"
    controller: "@coreshop.frontend.controller.payment:prepareCapture"
    variables: _locale,order
    priority: 2

  coreshop_checkout_error:
    pattern: "/(\\w+)\\/shop\\/checkout-error$/"
    reverse: "/%_locale/shop/checkout-error"
    controller: "@coreshop.frontend.controller.checkout:error"
    variables: _locale
    priority: 2

  coreshop_switch_currency:
    pattern: "/(\\w+)\\/shop\\/switch-currency\\/(.*)$/"
    reverse: "/%_locale/shop/switch-currency/%currencyCode"
    controller: "@coreshop.frontend.controller.currency:switch"
    variables: _locale,currencyCode
    priority: 2

  coreshop_register:
    pattern: "/(\\w+)\\/shop\\/register$/"
    reverse: "/%_locale/shop/register"
    controller: "@coreshop.frontend.controller.register:register"
    variables: _locale
    priority: 2

  coreshop_customer_profile:
    pattern: "/(\\w+)\\/shop\\/customer\\/profile$/"
    reverse: "/%_locale/shop/customer/profile"
    controller: "@coreshop.frontend.controller.customer:profile"
    variables: _locale
    priority: 2

  coreshop_customer_orders:
    pattern: "/(\\w+)\\/shop\\/customer\\/orders$/"
    reverse: "/%_locale/shop/customer/orders"
    controller: "@coreshop.frontend.controller.customer:orders"
    variables: _locale
    priority: 2

  coreshop_customer_order_detail:
    pattern: "/(\\w+)\\/shop\\/customer\\/order\\/([0-9]+)$/"
    reverse: "/%_locale/shop/customer/order/%order"
    controller: "@coreshop.frontend.controller.customer:orderDetail"
    variables: _locale,order
    priority: 2

  coreshop_customer_addresses:
    pattern: "/(\\w+)\\/shop\\/customer\\/addresses$/"
    reverse: "/%_locale/shop/customer/addresses"
    controller: "@coreshop.frontend.controller.customer:addresses"
    variables: _locale
    priority: 2

  coreshop_customer_address_edit:
    pattern: "/(\\w+)\\/shop\\/customer\\/address\\/(.*?)\\~a([0-9]+)$/"
    reverse: "/%_locale/shop/customer/address/%name~a%address"
    controller: "@coreshop.frontend.controller.customer:address"
    variables: _locale,name,address
    priority: 2

  coreshop_customer_address_new:
    pattern: "/(\\w+)\\/shop\\/customer\\/address\\/new$/"
    reverse: "/%_locale/shop/customer/address/new"
    controller: "@coreshop.frontend.controller.customer:address"
    variables: _locale
    priority: 3

  coreshop_customer_address_delete:
    pattern: "/(\\w+)\\/shop\\/customer\\/addresses\\/delete\\/([0-9]+)$/"
    reverse: "/%_locale/shop/customer/addresses/delete/%address"
    controller: "@coreshop.frontend.controller.customer:addressDelete"
    variables: _locale,address
    priority: 4

  coreshop_customer_settings:
    pattern: "/(\\w+)\\/shop\\/customer\\/settings$/"
    reverse: "/%_locale/shop/customer/settings"
    controller: "@coreshop.frontend.controller.customer:settings"
    variables: _locale
    priority: 2

  coreshop_customer_change_password:
    pattern: "/(\\w+)\\/shop\\/customer\\/change-password$/"
    reverse: "/%_locale/shop/customer/change-password"
    controller: "@coreshop.frontend.controller.customer:changePassword"
    variables: _locale
    priority: 2

  coreshop_customer_password_reset_request:
    pattern: "/(\\w+)\\/shop\\/password-reset-request$/"
    reverse: "/%_locale/shop/password-reset-request"
    controller: "@coreshop.frontend.controller.register:passwordResetRequest"
    variables: _locale
    priority: 6

  coreshop_customer_password_reset:
    pattern: "/(\\w+)\\/shop\\/password-reset$/"
    reverse: "/%_locale/shop/password-reset"
    controller: "@coreshop.frontend.controller.register:passwordReset"
    variables: _locale
    priority: 5

  coreshop_customer_confirm_newsletter:
    pattern: "/(\\w+)\\/shop\\/customer\\/confirm-newsletter$/"
    reverse: "/%_locale/shop/customer/confirm-newsletter"
    controller: "@coreshop.frontend.controller.customer:confirmNewsletter"
    variables: _locale
    priority: 2

  coreshop_search:
    pattern: "/(\\w+)\\/shop\\/search$/"
    reverse: "/%_locale/shop/search"
    controller: "@coreshop.frontend.controller.search:search"
    variables: _locale
    priority: 2

  coreshop_wishlist_summary:
    pattern: "/(\\w+)\\/shop\\/wishlist$/"
    reverse: "/%_locale/shop/wishlist"
    controller: "@coreshop.frontend.controller.wishlist:summary"
    variables: _locale
    priority: 2

  coreshop_wishlist_add:
    pattern: "/(\\w+)\\/shop\\/wishlist\\/add\\/([0-9]+)$/"
    reverse: "/%_locale/shop/wishlist/add/%product"
    controller: "@coreshop.frontend.controller.wishlist:addItem"
    variables: _locale,product
    priority: 3

  coreshop_wishlist_remove:
    pattern: "/(\\w+)\\/shop\\/wishlist\\/remove\\/([0-9]+)$/"
    reverse: "/%_locale/shop/wishlist/remove/%product"
    controller: "@coreshop.frontend.controller.wishlist:removeItem"
    variables: _locale,product
    priority: 3
