coreshop_shop_index:
  path: "%coreshop.frontend.base.url%"
  defaults:
    _controller: CoreShopFrontendBundle:Index:index

coreshop_shop_switch_currency:
  path: "%coreshop.frontend.base.url%/currency-switch/{currencyCode}"
  methods: [GET]
  defaults:
    _controller: coreshop.frontend.controller.currency:switchAction

coreshop_shop_cart_summary:
  path: "%coreshop.frontend.base.url%/cart"
  methods: [GET]
  defaults:
    _controller: coreshop.frontend.controller.cart:summaryAction

coreshop_shop_add_cart_item:
  path: "%coreshop.frontend.base.url%/cart/add/{productId}"
  methods: [GET]
  defaults:
    _controller: coreshop.frontend.controller.cart:addItemAction

coreshop_shop_add_cart_price_rule:
  path: "%coreshop.frontend.base.url%/cart/add-price-rule"
  methods: [GET]
  defaults:
    _controller: coreshop.frontend.controller.cart:addPriceRuleAction

coreshop_shop_remove_cart_price_rule:
  path: "%coreshop.frontend.base.url%/cart/remove-price-rule"
  methods: [GET]
  defaults:
    _controller: coreshop.frontend.controller.cart:removePriceRuleAction

coreshop_shop_remove_cart_item:
  path: "%coreshop.frontend.base.url%/cart/remove/{cartItemId}"
  methods: [GET]
  defaults:
    _controller: coreshop.frontend.controller.cart:removeItemAction

coreshop_shop_category_index:
  path: "%coreshop.frontend.base.url%/{name}~c{categoryId}"
  defaults: { _controller: coreshop.frontend.controller.category:indexAction}
  requirements:
    categoryId: \d+

coreshop_shop_product_detail:
  path: "%coreshop.frontend.base.url%/{name}~p{productId}"
  defaults: { _controller: coreshop.frontend.controller.product:detailAction}
  requirements:
    productId: \d+

coreshop_shop_login:
  path: "%coreshop.frontend.base.url%/login"
  defaults: { _controller: coreshop.frontend.controller.security:loginAction }

coreshop_shop_logout:
  path: "%coreshop.frontend.base.url%/logout"
  methods: [GET]

coreshop_shop_login_check:
  path: "%coreshop.frontend.base.url%/login-check"
  methods: [POST]
  defaults:
    _controller: coreshop.frontend.controller.security:checkAction

coreshop_shop_checkout:
  path: "%coreshop.frontend.base.url%/checkout/{stepIdentifier}"
  methods: [GET,POST]
  defaults:
    _controller: coreshop.frontend.controller.checkout:processAction

coreshop_shop_perform_checkout:
  path: "%coreshop.frontend.base.url%/perform-checkout"
  methods: [GET]
  defaults:
    _controller: coreshop.frontend.controller.checkout:doCheckoutAction

coreshop_shop_payment:
  path: "%coreshop.frontend.base.url%/pay/{orderId}"
  methods: [GET]
  defaults:
    _controller: coreshop.frontend.controller.payment:prepareCaptureAction

coreshop_shop_payment_after_pay:
  path: "%coreshop.frontend.base.url%/after-pay"
  methods: [GET, POST]
  defaults:
    _controller: coreshop.frontend.controller.payment:afterCaptureAction

coreshop_shop_order_thank_you:
  path: "%coreshop.frontend.base.url%/thank-you"
  methods: [GET]
  defaults:
    _controller: coreshop.frontend.controller.checkout:thankYouAction

coreshop_shop_checkout_error:
  path: "%coreshop.frontend.base.url%/error"
  methods: [GET]
  defaults:
    _controller: coreshop.frontend.controller.checkout:errorAction